### ISSUE TITLE
pokebank pass

### ISSUE THREAD

**Issue by paf2014** [zaksabeast/Transporter-PKSM-Bank-Patch#1]
I'd like to use the transporter_PKSM-bank_patch to send some pokemon to gen2 games to PKSM.I read the instructions but how could I do what is there if my pass in pokebank has already expired?Is this possible?

**Comment by zaksabeast** [comment]
Sorry but no, I'm not going to support bypassing subscription payments.  You will need to pay to use PokeBank.
