### ISSUE TITLE
Poketransporter 

### ISSUE THREAD

**Issue by paf2014** [zaksabeast/Transporter-PKSM-Bank-Patch#2]
So there is no use on this.because if you only can use poketransporter with an ative acccount to send them to pksm, you could use it to transfer to pokebank instead.sorry
if I erase my NNID and put another one in my 3ds, could I use poketransper for free at least for a trial period?

**Comment by zaksabeast** [comment]
I do not know.

Please only open issues if this patch isn't working as expected.  There are better places to ask questions about general Transporter use.
